name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  open-api-key:
    description: 'OpenAPI Token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'